TeamBASED/Hotel-Molveno

app/Http/Controllers/ReservationController.php
app/Models/Contact.php
app/Models/Reservation.php
app/Models/ReservationRoom.php
resources/scss/pages/_reservation-edit.scss
resources/views/components/room/available-rooms.blade.php
resources/views/reservation/edit.blade.php
resources/views/reservation/info.blade.php

Made functionality that shows which rooms are available and which rooms are in the current reservation. The front end of the reservation edit page has to  be adjusted

Overview available rooms

---

app/Http/Controllers/RoomController.php
app/Models/ReservationRoom.php
app/Models/Room.php
resources/js/roomOverviewDetails.js
resources/views/components/room/card.blade.php
resources/views/room/info.blade.php
resources/views/room/overview.blade.php

Nu wordt de bed configuration data weer goed getoond in de overview en info pagina's

Display bed configuration data

---

app/Http/Controllers/RoomBedConfigurationController.php
app/Http/Controllers/RoomController.php
app/Models/BedConfiguration.php
app/Models/RoomBedConfiguration.php
resources/scss/pages/_room-create.scss
resources/scss/pages/_room-edit.scss
resources/views/room/create.blade.php
resources/views/room/edit.blade.php

Nu kan bed config data aangemaakt, bewerkt, en verwijderd worden.
Er is nog wel 1 ding niet af: er wordt niet gechecked of bedconfig data aangepast is in een room post request, dus er worden rows weggegooid en aangemaakt terwijl er niks van data veranderd.

Bed configuration crud fix

---

app/Http/Controllers/ReservationController.php
app/Models/Room.php
resources/views/components/room/infobox.blade.php

bed type & amount wordt geladen in create en edit pagina's

Show bed config in reservation crud pages

---

resources/scss/components/_header.scss
resources/views/components/layout/header.blade.php
routes/web.php

Logo is nu een link, en ik heb de layout aangepast, het logo & de nav buttons staan nu even ver van de rand af als de padding van '.main-content' css class

Header logo link

---

app/Http/Controllers/ReservationController.php
app/Models/Guest.php
app/Models/Reservation.php
resources/views/components/buttons/edit-button.blade.php
resources/views/reservation/info.blade.php

Replace placeholder in reservation info with real guest data. Also made route to the corresponding guest edit page

Show guests in reservation info

---

app/Http/Controllers/ContactController.php
resources/js/roomOverviewDetails.js
resources/scss/components/_buttons.scss
resources/scss/pages/_room-edit.scss
resources/scss/pages/_room-overview.scss
resources/views/components/buttons/tertiary-button.blade.php
resources/views/room/create.blade.php
resources/views/room/edit.blade.php
resources/views/room/info.blade.php
resources/views/room/overview.blade.php
routes/web.php

now the button components function as intended.
I've implemented them in all room pages, other area's will be done next on different branches

Refactor buttons on room pages

---

resources/scss/pages/_reservation-edit.scss
resources/views/reservation/contact.blade.php
resources/views/reservation/create.blade.php
resources/views/reservation/edit.blade.php
resources/views/reservation/info.blade.php
resources/views/reservation/overview.blade.php

layout en buttons komen nu overeen, functionaliteit nog niet getest ik heb nu gesprek doeiii

Refactor reservation pages buttons

---

resources/scss/base/_typography.scss
resources/scss/main.scss
resources/scss/pages/_home.scss
resources/views/home.blade.php
routes/web.php

Make route for home page. Functionality for buttons needs to be added still

Configure home page

---

resources/js/roomOverviewDetails.js
resources/scss/pages/_reservation-edit.scss
resources/scss/pages/_room-overview.scss
resources/views/guest/edit.blade.php
resources/views/reservation/edit.blade.php
resources/views/reservation/info.blade.php
resources/views/room/overview.blade.php

Op de home overview pagina werd het 'details' gedeelte niet goed getoond, en de reservation edit pagina had helemaal foute layout.
Dit is nu gefixed.

Fix page layout issues

---

app/Http/Controllers/ReservationController.php
app/Http/Controllers/RoomController.php
app/Models/Reservation.php
app/Models/Room.php
database/seeders/DatabaseSeeder.php
resources/scss/pages/_room-overview.scss
resources/views/home.blade.php
resources/views/room/overview.blade.php

Added check in and check out date to the home page to link to the room overview. The rooms in the overview are filtered on availability in the reservations. Also added the filters in the room overview page.

Add check in and check out to home page

---

resources/views/guest/create.blade.php
resources/views/guest/edit.blade.php
resources/views/reservation/info.blade.php

was echt kleine aanpassing, ik heb ook routes van cancel buttons aangepast om naar reservation info page terug te gaan.

Add guest to existing reservation

---

resources/scss/abstracts/_variables.scss
resources/scss/components/_buttons.scss
resources/scss/components/_header.scss
resources/scss/components/_input-field.scss
resources/scss/pages/_guest-edit.scss
resources/scss/pages/_reservation-edit.scss
resources/scss/pages/_reservation-overview.scss
resources/scss/pages/_room-overview.scss
resources/scss/pages/_user-overview.scss
resources/views/components/delete-confirmation.blade.php
resources/views/components/room/available-rooms.blade.php
resources/views/guest/create.blade.php
resources/views/guest/edit.blade.php
resources/views/reservation/create.blade.php
resources/views/reservation/edit.blade.php
resources/views/reservation/overview.blade.php
resources/views/room/create.blade.php
resources/views/room/edit.blade.php
resources/views/user/edit.blade.php
resources/views/user/overview.blade.php

buttons hebben hover, posities op pagina's zijn beter.
ook de route prop van delete confirmation veranderd naar het volle "route()" ding, dit werkt beter

Improve styling

---

resources/js/passwordVisibilityToggle.js
resources/scss/pages/_login.scss
resources/scss/pages/_room-overview.scss
resources/scss/pages/_user-register.scss
resources/views/auth/login.blade.php
resources/views/components/layout/header.blade.php
resources/views/reservation/info.blade.php
resources/views/reservation/overview.blade.php
resources/views/room/overview.blade.php
resources/views/user/register.blade.php

Order of nav links in header, Show password input, fix typo's etc.

Integrate ui feedback

---

app/Http/Controllers/ContactController.php
app/Http/Controllers/HomeController.php
app/Http/Controllers/ReservationController.php
app/Http/Controllers/RoomController.php
resources/views/components/room/available-rooms.blade.php
resources/views/home.blade.php
resources/views/reservation/contact.blade.php
resources/views/reservation/create.blade.php
routes/web.php

Made the functionality to create a reservation from the home page, both view available rooms and direct creation of reservation is added

Make reservation from home page

---

app/Http/Controllers/CostAdjustmentController.php
app/Http/Controllers/PaymentMethodController.php
app/Models/CostAdjustment.php
app/Models/Invoice.php
app/Models/PaymentMethod.php
app/Models/Reservation.php
database/factories/CostAdjustmentFactory.php
database/factories/InvoiceFactory.php
database/migrations/2023_03_17_100627_create_invoices_table.php
database/migrations/2023_05_08_143609_create_payment_methods_table.php
database/migrations/2023_05_10_104217_create_cost_adjustments_table.php
database/seeders/CostAdjustmentSeeder.php
database/seeders/DatabaseSeeder.php
database/seeders/InvoiceSeeder.php
database/seeders/PaymentMethodSeeder.php

Filled in columns and database seeding for invoices, and added a payment methods table

Setup invoices

---

app/Models/Room.php
resources/views/room/info.blade.php

In the room info page, the placeholders for the upcoming reservations are updated, so that the actual upcoming reservations are displayed

add upcoming reservations to room info page

---

app/Http/Controllers/InvoiceController.php
resources/views/invoice/edit.blade.php

De data van invoices zelf kunnen nu aangepast worden, maar nog niet extra kosten, dat lijkt me wat lastiger dus heb ik het opgesplitst

Invoice update functionality

---

app/Http/Controllers/CostAdjustmentController.php
resources/views/invoice/edit.blade.php
routes/web.php

er kunnen nu cost adjustments toegevoegd worden met bedrag en beschrijving, geen styling gedaan voor de rest want hier is niet echt tijd voor

Add invoice cost adjustments

---

resources/views/invoice/edit.blade.php
resources/views/invoice/info.blade.php

de betalingen pagina's zijn nu wat leesbaarder, als het goed is.

Small front end improvements
